
validations:
  - name: "DNS_Armor_GCP_query"
    source:
      type: table
      environment: PREPROD
      schema: edw_stage
      table: stg_dns_armor_gcp_query
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: dns_armor_gcp_query
    primary_keys: time_to
    output_dir: ./results/DNS_Armor_GCP

  - name: "DNS_Armor_GCP_query_region_split"
    source:
      type: table
      environment: PREPROD
      schema: edw_stage
      table: stg_dns_armor_gcp_query_region_split
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: dns_armor_gcp_query_region_split
    primary_keys: time_to
    output_dir: ./results/DNS_Armor_GCP

  - name: "DNS_Armor_GCP_monthly_consumption"
    source:
      type: table
      environment: PREPROD
      schema: edw_stage
      table: stg_dns_armor_monthly_consumption
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: dns_armor_monthly_consumption
    primary_keys: obscured_account_id, obscured_organization_id, active_unique_project_count, royalty_due, active_unique_workload_count,total_queries_count, usage_month
    output_dir: ./results/DNS_Armor_GCP
