validations:
  - name: "Salesforce QuoteHistory"
    source:
      type: file
      path: ./raw_data/sfdc-quotehistory/quotehistory.csv
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: salesforce_quotehistory
    primary_keys: id
    output_dir: ./results/
